exports.categories = [
  "2D design",
  "3D design",
  "Agile",
  "Android",
  "Annoncaement",
  "Arduino",
  "Artificial intelligence",
  "Back-end",
  "BeBsata",
  "Business",
  "CAT",
  "Cloud computing",
  "Companies",
  "Creative commons",
  "Database",
  "Design patterns",
  "Education",
  "Embedded systems",
  "Entrepreneur",
  "Front-end",
  "Fun",
  "Game development",
  "Google",
  "Graphics",
  "Hardware",
  "Infographic",
  "Java",
  "Linux",
  "Marketing",
  "Mozila",
  "Networks",
  "New technology",
  "Open source",
  "Operating systems",
  "Php",
  "Programming",
  "Python",
  "Questions",
  "Remoting",
  "Security",
  "Smartphones development",
  "Social network",
  "Software",
  "Startups",
  "Tech-news",
  "Technology",
  "Ubuntu",
  "Uncategorized",
  "Virtualization",
  "Web",
  "Weekly versions",
  "Yahoo",
  "النسخة الاسبوعية"
];

exports.tags = [
  "3d",
  "android",
  "Artificial intelligence",
  "back-end",
  "Bebsata",
  "Business",
  "CAT",
  "Catazine",
  "Cloud",
  "Color theory",
  "Database",
  "Design",
  "Entrepreneur",
  "Event",
  "Fahemmny",
  "Framework",
  "Front-end",
  "Fun",
  "Game",
  "Google",
  "Graphics",
  "Hardware",
  "Infographic",
  "Internet",
  "Java",
  "Javascript",
  "Linux",
  "Network",
  "Networking",
  "Networks",
  "New technology",
  "Open source",
  "Operatting-systems",
  "Php",
  "Python",
  "RedHat",
  "Report",
  "Security",
  "Smartphone development",
  "Software",
  "Technology",
  "Ubuntu",
  "Web",
  "Weekly Version"
];
